name: Run .NET 6 Tests on Ubuntu Latest (Manual SDK & Runtime + Diagnostics)

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install native dependencies for .NET 6 on Ubuntu 24.04
        run: |
          sudo apt-get update
          sudo apt-get install -y libicu70 libssl1.1 libkrb5-3 zlib1g || true

      - name: Install .NET 6 SDK manually
        run: |
          wget https://dot.net/v1/dotnet-install.sh -O dotnet-install.sh
          chmod +x dotnet-install.sh
          ./dotnet-install.sh --channel 6.0 --install-dir "$HOME/.dotnet"
        env:
          DOTNET_INSTALL_DIR: $HOME/.dotnet

      - name: Setup .NET CLI path
        run: |
          echo "DOTNET_ROOT=$HOME/.dotnet" >> $GITHUB_ENV
          echo "$HOME/.dotnet" >> $GITHUB_PATH

      - name: Add global.json to lock SDK
        run: |
          echo '{ "sdk": { "version": "6.0.420", "rollForward": "disable" } }' > global.json

      - name: Verify .NET installation
        run: $HOME/.dotnet/dotnet --info

      - name: Restore
        run: $HOME/.dotnet/dotnet restore NetStandartOnUbuntuLatestRiset.sln

      - name: Debug Build (full verbosity)
        run: $HOME/.dotnet/dotnet build NetStandartOnUbuntuLatestRiset.sln --configuration Release --no-restore -v diag

      - name: Run Tests
        run: $HOME/.dotnet/dotnet test DbServicesTests/DbServicesTests.csproj --no-build --configuration Release --verbosity normal
